# Generated by Django 5.1.4 on 2025-01-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='Creado'),
        ),
    ]
