# Generated by Django 5.1.4 on 2025-01-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventario_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.CharField(max_length=150, verbose_name='Descripción'),
        ),
    ]
