# Generated by Django 5.1.4 on 2025-01-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_inventario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='num_factura',
            field=models.CharField(max_length=30, verbose_name='# factura'),
        ),
    ]
