# Generated by Django 5.1.4 on 2025-01-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resguardante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre marca')),
            ],
            options={
                'verbose_name': 'Resguardante',
                'verbose_name_plural': 'Resguardantes',
                'db_table': 'resguardante',
            },
        ),
    ]
