# Generated by Django 5.1.4 on 2025-01-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0002_color_created_factura_created_marca_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='no_factura',
            field=models.CharField(max_length=80, unique=True, verbose_name='# factura'),
        ),
    ]
